service: kani-keijiban-v2
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: test
  region: us-east-1
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
      Resource: 
        !GetAtt KaniKeijibanDB.Arn
        
plugins:
  - serverless-sync-s3buckets

custom:
  syncS3Buckets:
    - bucketRef: KaniKeijibanWebSitev2
      localDir: static
  tableName: KaniPosts

functions:
  getKeijibanPosts:
    handler: lambdas/endpoints/getKeijibanPosts.handler
    events:
      - http:
          path: api/posts/{id}
          method: get
          cors: true
  createKeijibanPosts:
    handler: lambdas/endpoints/createKeijibanPosts.handler
    events:
      - http:
          path: api/posts
          method: post
          cors: true
  updateKeijibanPosts:
    handler: lambdas/endpoints/updateKeijibanPosts.handler
    events:
      - http:
          path: api/posts/{id}
          method: put
          cors: true
  updateKeijibanComments:
    handler: lambdas/endpoints/updateKeijibanComments.handler
    events:
      - http:
          path: api/posts/comments/{id}
          method: put
          cors: true
  deleteKeijibanPosts:
    handler: lambdas/endpoints/deleteKeijibanPosts.handler
    events:
      - http:
          path: api/posts/{id}
          method: delete
          cors: true
  scanKeijibanPosts:
    handler: lambdas/endpoints/scanKeijibanPosts.handler
    events:
      - http:
          path: api/posts
          method: get
          cors: true
resources:
 Resources:
  KaniKeijibanWebSitev2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: yuuki-aws-dev.work
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  KaniKeijibanWebSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: KaniKeijibanWebSitev2
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 
              - s3:GetObject
            Resource:
              Fn::Join: [
                "", [
                  "arn:aws:s3:::",
                  {
                    "Ref": KaniKeijibanWebSitev2
                  },
                  "/*"
                ]
              ]
  KaniKeijibanDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
